### ISSUE TITLE
Latest libplist does not link properly

### ISSUE THREAD

**Issue by pekn** [libimobiledevice/libplist#157]
Latest libplist does not link properly

The following error occurs:
> ../src/.libs/libplist.so: undefined reference to `fmin'

(Tested with Ubuntu 18.04)

Should libplist link against libm as well?

**Comment by nikias** [comment]
Hi. It builds fine on x86_64, but it looks like there's a CPU instruction that handles it. Can you change `fmin` in the code to `__builtin_fmin` and see if that will make it work without libm?

**Comment by nikias** [comment]
Also according to this: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
GCC should automatically handle fmin and some others as builtin functions... so hmm...

**Comment by pekn** [comment]
I changed to __buildin_fmin and still gives same error.

**Comment by zinglax** [comment]
Out in left field here with this stuff but is fmin part of the math.h? if so
[this says to link the math library](https://doingmyprogramming.wordpress.com/2013/06/04/undefined-reference-to-math-h-functions-when-things-work-until-they-dont/)
by adding the -lm flags when compiling with gcc

**Comment by grubec** [comment]
I can confirm the error message on Ubuntu 18.04 on a x64 as well as arm architecture (raspian buster)

What struggles me is that I can't find the fmin in include/plist.h when I clone the master branch. It should be in with commit 303924413fcac2670dc6baf61d65d21545aa082f, according to the changes added in line 1250.

**Comment by nikias** [comment]
@grubec it's in plist.c not in plist.h
@zinglax @pekn I just pushed commit ce1092a5fc83e1b5590128b5f642200c382451a6 which should add `-lm` to the linker flags if required. Let me know if this works.

**Comment by grubec** [comment]
@nikias Thank you very much! ... just figured out my mistake as well ;)

**Comment by grubec** [comment]
tried it, but is still gives me a:
  CC       plistutil.o
  CCLD     plistutil
../src/.libs/libplist.so: undefined reference to `fmin'
collect2: error: ld returned 1 exit status
Makefile:418: recipe for target 'plistutil' failed
make[2]: *** [plistutil] Error 1

same as if I add -lm manually :(

**Comment by nikias** [comment]
Yes... I just started an old ubuntu 12.04 VM and it shows me the same. Working on it.

**Comment by nikias** [comment]
Can you try with commit https://github.com/libimobiledevice/libplist/commit/a2d66545d1303dd2cb5e0d56761aaf8a96bbc282 ?
Make sure to also do make clean and run autogen.sh again.

**Comment by grubec** [comment]
Yes, that did the trick.
Thanks @nikias

**Comment by nikias** [comment]
It also works on my ubuntu 18.04 x86_64 but my compiler just replaces it with a floating point CPU instruction 🤷‍♂️
With the check I added it will add -lm if required.
Anyway, @pekn it should also work for you now. Feel free to re-open if the problem persists.
